language: objective-c
osx_image: xcode7.2
xcode_workspace: TravisSSLTest.xcworkspace
xcode_scheme: TravisSSLTest
xcode_sdk: iphonesimulator
matrix:
  include:
    - osx_image: xcode7.1
    - osx_image: xcode7
before_install:
  - travis_wait pod repo update --verbose
install:
  - pod install
