language: objective-c
xcode_workspace: TravisSSLTest.xcworkspace
xcode_scheme: TravisSSLTest
xcode_sdk: iphonesimulator
matrix:
  include:
    - osx_image: xcode7.2
    - osx_image: xcode7.1
    - osx_image: xcode7
